repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-xml
    - id: check-added-large-files
- repo: https://github.com/maltzj/ktlint-pre-commit
  rev: e5bee17
  hooks:
  - id: ktlint
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.16.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
